# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [10]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: deploy
      uses: appleboy/ssh-action@master
      env:
        ACCESSKEYID: ${{ secrets.ACCESSKEYID }}
        ACCESSKEYSECRET: ${{ secrets.ACCESSKEYSECRET }}
      with:
        host: ${{ secret.HOST }}
        username: ${{ secret.USERNAME }}
        password: ${{ secret.PASSWORD }}
        port: ${{ secret.PORT }}
        envs: ACCESSKEYID,ACCESSKEYSECRET
        script:  |
          export ACCESSKEYID=$ACCESSKEYID
          export ACCESSKEYSECRET=$ACCESSKEYSECRET
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/bash_completion"
          cd /root/node-egg
          git pull origin master
          npm install --production
          npm run stop
          npm run start
